/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HashPastedImagePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/utils.ts
var crypto = __toESM(require("crypto"));
var hash = (contents) => crypto.createHash("sha512").update(contents).digest("hex");
var path = {
  join(...partSegments) {
    let parts = [];
    for (let i = 0, l = partSegments.length; i < l; i++) {
      parts = parts.concat(partSegments[i].split("/"));
    }
    const newParts = [];
    for (let i = 0, l = parts.length; i < l; i++) {
      const part = parts[i];
      if (!part || part === ".") continue;
      else newParts.push(part);
    }
    if (parts[0] === "") newParts.unshift("");
    return newParts.join("/");
  },
  basename(fullpath) {
    const sp = fullpath.split("/");
    return sp[sp.length - 1];
  },
  extension(fullpath) {
    const positions = [...fullpath.matchAll(/\./gi)].map((a) => a.index);
    return fullpath.slice(positions[positions.length - 1] + 1);
  }
};

// src/main.ts
var PASTED_IMAGE_PREFIX = "Pasted image ";
var HashPastedImagePlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (!(file instanceof import_obsidian.TFile)) return;
        const timeGapMs = (/* @__PURE__ */ new Date()).getTime() - file.stat.ctime;
        if (timeGapMs > 1e3) return;
        if (isMarkdownFile(file)) return;
        if (isPastedImage(file)) {
          this.startRenameProcess(file);
        }
      })
    );
  }
  async startRenameProcess(file) {
    var _a;
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      return;
    }
    const originName = file.name;
    const newName = this.generateNewName(file);
    const newPath = path.join(file.parent.path, newName);
    try {
      await this.app.fileManager.renameFile(file, newPath);
    } catch (err) {
      console.log(err);
      throw err;
    }
    const editor = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor;
    if (!editor) {
      return;
    }
    const cursor = editor.getCursor();
    const line = editor.getLine(cursor.line);
    const replacedLine = line.replace(originName, newName);
    editor.transaction({
      changes: [
        {
          from: { ...cursor, ch: 0 },
          to: { ...cursor, ch: line.length },
          text: replacedLine
        }
      ]
    });
  }
  generateNewName(file) {
    return hash(file.name + (/* @__PURE__ */ new Date()).toString()) + "." + file.extension;
  }
};
function isPastedImage(file) {
  if (file instanceof import_obsidian.TFile) {
    if (file.name.startsWith(PASTED_IMAGE_PREFIX)) {
      return true;
    }
  }
  return false;
}
function isMarkdownFile(file) {
  if (file instanceof import_obsidian.TFile) {
    if (file.extension === "md") {
      return true;
    }
  }
  return false;
}
